# SSHs into the server, creates a data backup, then applies code changes.

name: Deploy to Server

on:
  push:
    branches: [ production ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh deploy
        uses: appleboy/ssh-action@1d1b21ca96111b1eb4c03c21c14ebb971d2200f6
        with:
          # Private Key
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Remote host
          host: ${{ secrets.SSH_HOST }}
          # Remote user
          username: ${{ secrets.SSH_USER }}
          # Script
          script: |
            echo "Backing up database"
            cd /root/scripts/splite/
            ./splite-data-backup.sh
            echo "Backing up database complete"
            echo "Applying Changes"
            cd /root/apps/splite
            git pull -f
            echo "Applying Changes complete"
            docker-compose down
            docker-compose up -d          
